PROJECT_NAME: medpoint
PROJECT_ID: fgcoodkwldnvxcoqdufi
DEPLOYMENT_TARGET: cloud

ACCESS_TOKEN: sbp_448482039a3a30a2dea55880be42792e618da285
ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZnY29vZGt3bGRudnhjb3FkdWZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI4NjMzOTIsImV4cCI6MjA0ODQzOTM5Mn0.IZkaSqWOr4dHj0e_rkfh5rCP7NWWsZAGBLak55dUmaY
SERVICE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZnY29vZGt3bGRudnhjb3FkdWZpIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczMjg2MzM5MiwiZXhwIjoyMDQ4NDM5MzkyfQ.XiVujSJHckvgJsz_NKxi4CBEK4jyagamIs425LKb4Ak

SUPABASE_API_URL: https://api.supabase.com
SUPABASE_API_BASE_PATH: 
SUPABASE_PUBLIC_URL: https://fgcoodkwldnvxcoqdufi.supabase.co

SERVER_HOST: 127.0.01
SERVER_PORT: 8002

ENVIRONMENT: development
VERSION: 1.0.0

BREAKER_ENABLE: true

TRACE_ENABLE: false
TRACE_COLLECTOR: 
TRACE_COLLECTOR_ENDPOINT: 

CORS_ALLOWED_ORIGINS:
CORS_ALLOWED_METHODS:
CORS_ALLOWED_HEADERS:
